[package]
name = "goober-runner"
version.workspace = true
edition = "2021"

[dependencies]
gl = "0.14.0"
glutin = "0.31.1"
glutin-winit = "0.4.2"
goober-ui = { path = "../ui" }
raw-window-handle = "0.5.2"
tokio = { version = "1.33.0", features = ["rt", "sync", "time"] }
winit = "0.29.3"
