[package]
name = "goober-ui"
version = "0.1.0"
edition = "2021"

[dependencies]
skia-safe = { version = "0.68.0", optional = true }
goober-runtime.path = "../runtime"

[features]
skia = ["dep:skia-safe"]
skia-gpu = ["skia-safe?/gpu"]
skia-gl = ["skia-safe?/gl"]
default = ["skia"]
